
on:
  push:
    branches: [ main, sfinae, editor ]
  pull_request:
    branches: [ main, sfinae, editor ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get install doxygen graphviz

      - name: Generate Doxygen docs
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html  # Папка с HTML-документацией
          keep_files: false