name: C++ CI

on:
  push:
    branches: [main, bayan]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        echo "VCPKG_ROOT=$GITHUB_WORKSPACE/vcpkg" >> $GITHUB_ENV
        
    - name: Install dependencies
      run: |
        ./vcpkg/vcpkg install \
          boost-filesystem \
          boost-system \
          boost-program-options \
          boost-crc
        
    - name: Build
      run: |
        cmake -B build -S . \
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DWITH_GOOGLE_TEST=ON
        cmake --build build
        
    - name: Create package
      run: |
        cmake --build build --target package
        
    - name: Verify artifacts
      run: |
        ls -la build/
        [ -f build/bayan ] || exit 1
        [ -f build/*.deb ] || exit 1
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          build/bayan
          build/*.deb
    
    - name: Test
      run: |
        cd build
        ctest --output-on-failure